### ISSUE TITLE
Is there any generated function to revert from protobuf to edn?

### ISSUE THREAD

**Issue by naomijub** [protojure/protoc-plugin#62]
If not, have you thought about how to do it?
Something like `com.google.protobuf/Value->edn`

**Comment by ghaskins** [comment]
Hello @naomijub , I am not sure I understand the use case.  Could you elaborate?

**Comment by naomijub** [comment]
I have a `com.google.protobuf.Value` that looks like this:
```
#com.google.protobuf.Value-type{:kind 
                                {:struct-value 
                                 #com.google.protobuf.Struct-type{:fields 
                                                                  {wow #com.google.protobuf.Value-type{:kind 
                                                                                                       {:string-value effect}}, 
                                                                   xt/id #com.google.protobuf.Value-type{:kind 
                                                                                                         {:string-value fooBar}}}}}}
```

And I would like a generated function, `Value->edn`,  that could convert it into this:
```
{:wow "effect" :xt/id "fooBard"}
```

**Comment by naomijub** [comment]
I think your other project `[org.clojars.ghaskins/protobuf "3.4.0-1"]` does something like that but it requires the Java definitions of `com.google.protobuf.Value` right? @ghaskins

**Comment by ghaskins** [comment]
I see.  I've never really worked with the Value type before (the old clojars.ghaskins project was forked from somewhere else that probably needed/provided that helper).

You probably know this, but protojure just generates native defrecords, so all the clojure transforms are at your disposal.

E.g.

```
m
=>
#com.google.protobuf.Value-type{:kind {:struct-value #com.google.protobuf.Struct-type{:fields {"wow" #com.google.protobuf.Value-type{:kind {:string-value "effect"}},
                                                                                               "xt/id" #com.google.protobuf.Value-type{:kind {:string-value "fooBar"}}}}}}
(->> m :kind :struct-value :fields
    (reduce (fn [coll [k v]] (assoc coll (keyword k) (-> v :kind :string-value))) {}))
=> {:wow "effect", :xt/id "fooBar"}
```

That said, I assume you're looking for a more generalized solution.  Sadly, nothing exists like that today.  I have been contemplating adding some kind of utility lib to the google.protobuf definitions because I do often deal with Timestamp.  Perhaps Value->edn can be part of that, especially if you might be willing to contribute the code.
